name: User-Dev

on:
  push:
    branches: [ feature/* ]

  workflow_dispatch:

jobs:
  build:
    name: Install Dependencies, Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: |
            ~/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}
          restore-keys: ${{ runner.os }}-build-

      - name: Run Build
        run: yarn run build

      - name: Run Test
        run: yarn run test

      - name: Run e2e
        run: yarn run test:e2e
