name: User-Prod

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  build:
    if: success()
    name: Install Dependencies, Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: |
            ~/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('**/package.json') }}

      - name: Run Build
        run: yarn run build

      - name: Run Test
        run: yarn run test:cov

      - name: Run e2e
        run: yarn run test:e2e

  docker:
    if: success()
    name: Setup Docker and Push Image
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Generate Build Number
        id: buildId
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.GH_TOKEN}}

      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to latest
        id: docker_latest
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: toxictoast/twitch-user:latest

      - name: Build and push to build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: toxictoast/twitch-user:build-${{ steps.buildId.outputs.build_number  }}


      - name: Image digest
        run: echo ${{ steps.docker_latest.outputs.digest }}